### ISSUE TITLE
Not all binaries seems to be valid in misc-valid

### ISSUE THREAD

**Issue by pepyakin** [sunfishcode/wasm-collection#1]
Looks like `misc-valid/musl.wasm` isn't actually valid, because it uses 0x0d version.
Also, I guess `misc-valid/reloc.wasm` is only valid in linking context, because it uses `set_global` on immutable import.

**Comment by sunfishcode** [comment]
Thanks for pointing that out! I've now updated musl.wasm and removed reloc.wasm.
